#!/bin/bash
### Test if string is IP v4 address
# Credits :  https://github.com/marios-zindilis/Scripts/blob/master/Bash/is_ip.sh

if [ $(echo "$1" | grep -o '\.' | wc -l) -ne 3 ]; then
 exit 2;
elif [ $(echo "$1" | tr '.' ' ' | wc -w) -ne 4 ]; then
 exit 2;
else
for OCTET in $(echo $1 | tr '.' ' '); do
if ! [[ "$OCTET" =~ ^[0-9]+$ ]]; then
 exit 2;
elif [[ "$OCTET" -lt 0 || "$OCTET" -gt 255 ]]; then
 exit 2;
fi
done
fi
exit 0;

