#!/bin/bash
### return 0 if IP is valid IPv4 and if NOT already in IPset blacklists
# 2.0 - moved ip check to ipcalc-ng
# 1.2 - add verbose option
# 1.0 - add IP v4 string check
# 0.9 - search if ip address is already in a configured ipset lists

### Preset and vars
# refresh ipset all IP list for quick check
_LOGD='/root/blacklist/logs'
find ${_LOGD}/ipset-all.ip -mmin +60 -exec ipset save -f ${_LOGD}/ipset-all.ip \; || ipset save -f ${_LOGD}/ipset-all.ip
# check for installed ipcalc-ng
type ipcalc-ng &>/dev/null || { echo "ipcalc-ng not found.. exiting" && exit 1 ; }
_IP=''

_USAGE () {
echo "### Usage:"
echo "$0 192.168.1.1        # return 0 if \$1 is valid IPv4 address and if NOT already in IPset lists"
echo "$0 -v 192.168.1.1     # '-v' for verbose output"
echo
exit 2
}

while (( "$#" )); do
  case "$1" in
    -v|--verbose) _VERB='true'
      shift
      ;;
    -h|--help) _USAGE
      shift
      ;;
    -*|--*=) echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) _IP="$1"
      shift
      ;;
  esac
done
eval set -- "$_IP"

[ -z "$_IP" ] && _USAGE

_ISANIP(){
if [ "$_VERB" = 'true' ]; then
  ipcalc-ng -c $_IP || exit 1
else
  ipcalc-ng -cs $_IP || exit 1
fi
}

_ISINBL(){
for _LST in $(ipset list -n); do 
if [ "$_VERB" = 'true' ]; then
{ grep -m 1 -w $_IP ${_LOGD}/ipset-all.ip | grep $_LST && _FOUND=1 ; } || { ipset test $_LST $_IP && _FOUND=1 ; } 
else
{ grep -q -m 1 -w $_IP ${_LOGD}/ipset-all.ip | grep $_LST && _FOUND=1 ; } || { ipset test $_LST $_IP >/dev/null 2>&1 && _FOUND=1 ; } 
fi
done
echo
}

[ "$_VERB" = 'true' ] && echo "### Blacklist-Check IP = $_IP "
_ISANIP
_ISINBL
[ "$_FOUND" = 1 ] && exit 1
# return 0 if reach
exit 0
