#!/bin/bash

IP1=$1

# validate that test string is an IP
# Credits :  https://github.com/marios-zindilis/Scripts/blob/master/Bash/is_ip.sh
function is_IP() {
if [ $(echo "$1" | grep -o '\.' | wc -l) -ne 3 ]; then
 echo "'$1' does not look like an IP Address (does not contain 3 dots).";
 echo "### Usage ###"
 echo "$(basename $0) ip.ad.dr.es"
 exit 1;
elif [ $(echo "$1" | tr '.' ' ' | wc -w) -ne 4 ]; then
 echo "'$1' does not look like an IP Address (does not contain 4 octets).";
 echo "### Usage ###"
 echo "$(basename $0) ip.ad.dr.es"
 exit 1;
else
for OCTET in $(echo $1 | tr '.' ' '); do
if ! [[ "$OCTET" =~ ^[0-9]+$ ]]; then
 echo "'$1' is not an IP Address (octet '$OCTET' is not numeric).";
 echo "### Usage ###"
 echo "$(basename $0) ip.ad.dr.es"
 exit 1;
elif [[ "$OCTET" -lt 0 || "$OCTET" -gt 255 ]]; then
 echo "'$1' is not an IP Address (octet '$OCTET' in not in range 0-255).";
 echo "### Usage ###"
 echo "$(basename $0) ip.ad.dr.es"
 exit 1;
fi
done
fi
return 0;
}

# Search for IP address in every blacklist configured in IPSET and exit 0 for scripts
if is_IP "$IP1"; then
 for _LST in $(ipset list -n); do 
  ipset test $_LST $IP1 && exit 0
 done
else
 echo "### Usage ###"
 echo "$(basename $0) ip.ad.dr.es"
fi
