#!/bin/bash
### Check Honeypot listening and iptables chain position

# set target ipset list name:
_TGT=blocklists
# set iptables
_CHN="INPUT OUTPUT FORWARD"

# check if honeypot listen
if ! ss -tlpn|grep -wq '0:22 '; then 
telegram-send "[LTS] Honeypot port 22 NOT LISTENING"
fi

# check if blocklists chain is in 1st position (docker..) and correct if needed
for i in ${_CHN}; do
  if ! iptables -nvL ${i} 1|grep -q ${_TGT}; then
    iptables -D ${i} -j ${_TGT}
    iptables -I ${i} 1 -j ${_TGT}
    iptables -nvL ${i} 1|grep -q ${_TGT} && telegram-send "[LTS] Blocklist Chain position corrected" || telegram-send "[LTS] Blocklist Chain position correction FAILED"
  fi
done
