#!/bin/bash

_XLOG="/root/blacklist/honeypot.log"
_XPOR="/root/blacklist/horny-banlist"
_TMP=$(mktemp /root/blacklist/.hotmp.XXX)

# get IP address from honeypot log
grep from "$_XLOG" |awk '{print $4}'|grep ':'|awk -F: '{print $1}'|sort|uniq > "$_TMP"

# check if not already in a Blacklist and add to "hony" blacklist
for i in $(cat "$_TMP"); do
if ! blacklist-check $i > /dev/null 2>&1; then
ipset add honeypot "$i" && echo "$i # blacklisted $(date "+%d-%m-%Y %H:%M:%S")" >> "$_XPOR"
fi
done
rm $_TMP
> $_XLOG
