#!/bin/bash

_XLOG="/root/blacklist/honeypot.log"
_XPOR="/root/blacklist/horny-banlist"
_TMP1=$(mktemp /root/blacklist/.hotmp1.XXX)
_TMP2=$(mktemp /root/blacklist/.hotmp2.XXX)

# get IP address from honeypot log
cat "$_XLOG"|grep from > "$_TMP1"
sed -i 's/Ncat\://g' "$_TMP1"
cat "$_TMP1"|grep ':'|awk '{print $3}'|awk -F':' '{print $1}'|uniq > "$_TMP2"

# check if not already in a Blacklist and add to "hony" blacklist
for i in $(cat "$_TMP2"); do
blacklist-check $i > /dev/null 2>&1 || ipset add hony "$i" && echo "$i # blacklisted $(date "+%d-%m-%Y %H:%M:%S")" >> "$_XPOR"
done
