#!/bin/bash
### Simple Ncat Honeypot Port Trap
### v1.1 - Added logging
# specify port with "-p 8000" 
# default : 22/tcp

_XPORT='22'
_XLOG="/root/blacklist/honeypot.log"

while getopts :p: OPT; do
    case "${OPT}" in
          p) _XPORT="$OPTARG";;
     esac
done
# execute honeyban script when IP is knocking
while true; do
ncat -vl --keep-open $_XPORT --exec "/usr/local/bin/honeypot-banscript" &>> $_XLOG
done
